### ISSUE TITLE
Feature wolfram2desmos as a proper plugin

### ISSUE THREAD

**Issue by jared-hughes** [jared-hughes/DesModder#88]
Maybe want to fork wolfram2desmos to a desmodder-paste-asciimath plugin or contribute directly to wolfram2desmos.

This would fix two issues:
  - it can't be disabled currently (alleviated in next update with the ability to be disabled after page reload, but anyway)
  - it loads immediately instead of loading after Calc.controller etc is defined (which is handled in DesModder)

Probably want to discuss with @Heavenira

**Comment by SlimRunner** [comment]
I had been thinking of this as well because some minor glitches with w2d that could be easily circumvent with a quick disable.

If need be, I can take the task of refactoring the script next week. I would only need to know how it works better for Heavenira and you. Meaning either collaborate to update Heavenira's original repo, or creating a clone for Desmodder specifically.

**Comment by jared-hughes** [comment]
Loading w2d currently works by injecting the full script into the page, similarly to how Tampermonkey does it. This was a pain to set up.

On DesModder's end, it would be easiest to convert this to an ES6 module. It appears that `wolfram2desmosListener` is the initialization function, so you should be able to remove the timeout and export that function, Then an `index.ts` could import that function and export a configuration object (id, name, description, onEnable, onDisable, enabledByDefault) to DesModder.

I'm not sure if Heavenira wants to maintain compatibility with tampermonkey, so looping him in @Heavenira.

But for now, you should be able to fork the repository to SlimRunner/desmodder-wolfram2desmos (or perhaps desmodder-paste-asciimath which makes more sense), and we can roll from that one until it (maybe) gets merged to Heavenira/wolfram2desmos

**Comment by Heavenira** [comment]
Truth be told, the _injection_ of Wolfram2Desmos is really something that is beyond me. My main contribution to the project is the wolfram2desmos() function itself, however I have no idea on how to hook it into Desmos elegantly. That was completely with the help of @SlimRunner , who without, the addon wouldn't have even existed.

I think it would be the best idea if @jared-hughes and @SlimRunner could create a "Desmos Paste Overwrider", which is essentially takes the predefines wolfram2desmos() function and injects it with DesModder seamlessly. This is the only part which I can't help on, I'm not too fluent in JS.

This way I can improve the algorithm (it could *really* use some improvements, these last few months have revealed tons of glitches), and it could work well with DesModder.

If you'd like to make a fork, then I will completely support that decision! Please make wolfram2desmos as seamlessly integrated as possible, so that it doesn't take forever to startup. That way I can work on the algorithm (just after school, I have been really swamped as of late).

**Comment by Heavenira** [comment]
Also, DesModder should be a 100% priority. I truly believe that more people should gravitate towards DesModder over individualized Tampermonkey scripts.

**Comment by jared-hughes** [comment]
Sounds like a consensus. 

 1. @SlimRunner will fork Heavenira/wolfram2desmos and edit to let it integrate with DesModder. I can help with this too. When it's ready, he'll send a PR back to the main repository
 2. @Heavenira would merge the request into Heavenira/wolfram2desmos and potentially rename the repository to Heavenira/desmodder-paste-asciimath
 3. When all is ready, I will update submodules and imports in the main DesModder repository

**Comment by FabriceNeyret** [comment]
so, waiting for that, it's apparently off for now, so we have to activate the script again.  right ?

**Comment by jared-hughes** [comment]
If you have DesModder installed, then you should leave the wolfram2desmos userscript OFF in Tampermonkey.

The discussion here refers to specifically changing how wolfram2desmos hooks into DesModder to allow it to be disabled and fix a couple other issues.

**Comment by FabriceNeyret** [comment]
Yes, I know. I just mean the option "wolfram2desmos" appears in grey in DesModder; I though it was an consequence of what you mentioned here. ( I should have checked that it was still working, though ).

**Comment by jared-hughes** [comment]
Ah yes, the toggle has been gray (disabled) from the beginning because the plugin could not be disabled with the old injection system.

**Comment by jared-hughes** [comment]
Closed by #94
